"""empty message

Revision ID: 045b12e4626a
Revises: 
Create Date: 2021-12-26 15:38:12.696687

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '045b12e4626a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('work_day', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_is_done'), 'tasks', ['is_done'], unique=False)
    op.create_index(op.f('ix_tasks_work_day'), 'tasks', ['work_day'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_work_day'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_done'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
