name: Unit Tests and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "pypy3"]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: false

    - name: Install dependencies
      run: |
        make requirements
    - name: Run lint
      run: |
        make lint
    - name: Run tests
      run: |
        make test
